/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.javaevents.ventanas;

import java.awt.Font;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import poo.javaevents.clases.Buscador;
import poo.javaevents.clases.Datos;
import poo.javaevents.clases.Direccion;
import poo.javaevents.clases.Evento;

/**
 *
 * @author golde
 */
public class BusquedaEventos extends javax.swing.JFrame {

    /**
     * Creates new form BusquedaEventos
     */
    public BusquedaEventos() {
        initComponents();

        Datos.eventos.add(new Evento(
                "Concierto de Coldplay",
                "Concierto",
                new Direccion("Av. Música", 123, "Madrid", 28013),
                new ArrayList<>(List.of(
                        LocalDateTime.of(2025, 6, 20, 21, 0),
                        LocalDateTime.of(2025, 6, 21, 21, 0)
                )),
                75.50,
                "/src/main/recursos/imagenes/coldplay.jpg",
                4.8
        ));

        Datos.eventos.add(new Evento(
                "Final de la Champions",
                "Deporte",
                new Direccion("Estadio Nacional", 1, "Barcelona", 8002),
                new ArrayList<>(List.of(
                        LocalDateTime.of(2025, 5, 30, 20, 45)
                )),
                120.00,
                "/recursos/champions.png",
                4.9
        ));

        Datos.eventos.add(new Evento(
                "Musical El Rey León",
                "Musical",
                new Direccion("Gran Vía", 45, "Madrid", 28013),
                new ArrayList<>(List.of(
                        LocalDateTime.of(2025, 7, 5, 19, 30),
                        LocalDateTime.of(2025, 7, 6, 19, 30),
                        LocalDateTime.of(2025, 7, 7, 19, 30)
                )),
                55.00,
                "/recursos/reyLeon.png",
                4.7
        ));

        Datos.eventos.add(new Evento(
                "Teatro Hamlet",
                "Teatro",
                new Direccion("Calle Teatro Clásico", 8, "Sevilla", 41001),
                new ArrayList<>(List.of(
                        LocalDateTime.of(2025, 6, 15, 20, 0),
                        LocalDateTime.of(2025, 6, 16, 20, 0)
                )),
                30.00,
                "/recursos/hamlet.png",
                4.2
        ));

        Datos.eventos.add(new Evento(
                "Festival Primavera Sound",
                "Concierto",
                new Direccion("Parc del Fòrum", 1, "Barcelona", 8019),
                new ArrayList<>(List.of(
                        LocalDateTime.of(2025, 6, 3, 16, 0),
                        LocalDateTime.of(2025, 6, 4, 16, 0),
                        LocalDateTime.of(2025, 6, 5, 16, 0)
                )),
                95.00,
                "/recursos/primaveraSound.png",
                4.5
        ));

        Datos.eventos.add(new Evento(
                "Partido NBA Europe",
                "Deporte",
                new Direccion("WiZink Center", 1, "Madrid", 28009),
                new ArrayList<>(List.of(
                        LocalDateTime.of(2025, 10, 10, 20, 0),
                        LocalDateTime.of(2025, 10, 11, 20, 0)
                )),
                110.00,
                "/recursos/nbaEurope.png",
                4.6
        ));

        // Crear un modelo DefaultTableModel para poder añadir filas
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{"Título", "Tipo", "Ciudad"}, 0
        );

        // Aplicar el modelo a la tabla creada
        tablaEventos.setModel(modelo);
        
        // Hacer las filas más altas y la fuente más grande
        tablaEventos.setRowHeight(30);
        tablaEventos.setFont(new Font("Segoe UI", Font.PLAIN, 16));

        // Añadir todos los eventos de la lista de Datos.eventos a la tabla
        for (Evento e : Datos.eventos) {
            Object[] fila = {
                e.getTitulo(),
                e.getTipo(),
                e.getDireccion().getCiudad()
            };

            modelo.addRow(fila);
        }
        
        // Copiar la lista de todos los eventos a eventosEncontrados por si el
        // usuario no utiliza ningún filtro ni hace ninguna búsqueda
        eventosEncontrados = (ArrayList<Evento>) Datos.eventos.clone();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JavaEvents = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEventos = new javax.swing.JTable();
        campoBuscador = new javax.swing.JTextField();
        etiquetaBuscarPor = new javax.swing.JLabel();
        tipoBusqueda = new javax.swing.JComboBox<>();
        botonBuscar = new javax.swing.JButton();
        etiquetaFiltro = new javax.swing.JLabel();
        botonDetalles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JavaEvents.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JavaEvents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JavaEvents.setText("JavaEvents");

        tablaEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Tipo", "Ciudad"
            }
        ));
        jScrollPane1.setViewportView(tablaEventos);

        etiquetaBuscarPor.setText("Buscar por:");

        tipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Título", "Tipo", "Ciudad" }));
        tipoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoBusquedaActionPerformed(evt);
            }
        });

        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        etiquetaFiltro.setText("Flitro: Ninguno");

        botonDetalles.setText("Ver detalles");
        botonDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetallesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JavaEvents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoBuscador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(etiquetaBuscarPor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(160, 160, 160))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaFiltro)
                            .addComponent(botonDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(JavaEvents)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etiquetaBuscarPor)
                        .addComponent(tipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(etiquetaFiltro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonDetalles)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // Obtener el modelo de la tabla y borrar todas las filas
        DefaultTableModel modelo = ((DefaultTableModel) tablaEventos.getModel());
        modelo.setRowCount(0);

        // Obtener el filtro aplicado
        String filtro = tipoBusqueda.getSelectedItem().toString();

        // Borrar la lista de eventosEncontrados para llenarla con los nuevos
        eventosEncontrados.clear();
        
        // Añadir los eventos encontrados
        switch (filtro) {
            case "Título":
                eventosEncontrados = Buscador.buscarPorTitulo(campoBuscador.getText());
                etiquetaFiltro.setText("Filtro: Título");
                break;

            case "Tipo":
                eventosEncontrados = Buscador.buscarPorTipo(campoBuscador.getText());
                etiquetaFiltro.setText("Filtro: Tipo");
                break;
                
            case "Ciudad":
                eventosEncontrados = Buscador.buscarPorCiudad(campoBuscador.getText());
                etiquetaFiltro.setText("Filtro: Ciudad");
                break;
        }
        
        // Añadir de nuevo los eventos a la tabla
        for (Evento e : eventosEncontrados) {
            Object[] fila = {
                e.getTitulo(),
                e.getTipo(),
                e.getDireccion().getCiudad()
            };

            modelo.addRow(fila);
                    
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void tipoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoBusquedaActionPerformed

    private void botonDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetallesActionPerformed
        // Obtener el modelo de la tabla
        DefaultTableModel modelo = ((DefaultTableModel) tablaEventos.getModel());
        
        // Ver cual es el evento que tiene elejido el usuario
        int filaElejida = tablaEventos.getSelectedRow(); // Fila seleccionada
        eventoElejido = eventosEncontrados.get(filaElejida);
        
        // Crear una ventana que muestre los detalles del evento
        DetallesEvento detallesEvento = new DetallesEvento();
        detallesEvento.setLocationRelativeTo(this);
        detallesEvento.setVisible(true);
        
        // Modificar los atributos de la ventana para que correspondan a los
        // elementos del evento seleccionado
        detallesEvento.setEtiquetaTitulo(eventoElejido.getTitulo());
        
        detallesEvento.setEtiquetaTipoEvento(eventoElejido.getTipo());
        
        String calle = eventoElejido.getDireccion().getCalle();
        int numero = eventoElejido.getDireccion().getNumero();
        String ciudad = eventoElejido.getDireccion().getCiudad();
        int codPostal = eventoElejido.getDireccion().getCodPostal();
        detallesEvento.setEtiquetaAtributosDireccion("Calle: " + calle + ", " +
                numero + ". " + "Ciudad: " + ciudad + ", " + codPostal);
        
        detallesEvento.setHorarios(eventoElejido.getFechasYHoras());
        
        try { 
            detallesEvento.setImagen(eventoElejido.getPortada());
        } catch (Exception e) {
            System.out.println("LA IMAGEN ESTÁ MAL");
        }
        
        detallesEvento.setEventoElejido(eventoElejido);
        System.out.println("be" + eventoElejido);
    }//GEN-LAST:event_botonDetallesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedaEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedaEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedaEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedaEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusquedaEventos().setVisible(true);
            }
        });
    }
    
    public Evento getEventoElejido() {
        return eventoElejido;
    }

    private ArrayList<Evento> eventosEncontrados;
    private Evento eventoElejido;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JavaEvents;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonDetalles;
    private javax.swing.JTextField campoBuscador;
    private javax.swing.JLabel etiquetaBuscarPor;
    private javax.swing.JLabel etiquetaFiltro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEventos;
    private javax.swing.JComboBox<String> tipoBusqueda;
    // End of variables declaration//GEN-END:variables
}
