/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poo.javaevents.ventanas;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import poo.javaevents.clases.Evento;

/**
 *
 * @author golde
 */
public class DetallesEvento extends javax.swing.JFrame {

    /**
     * Creates new form DetallesEvento
     */
    public DetallesEvento() {
        initComponents();
        setSize(550, 700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JavaEvents = new javax.swing.JLabel();
        etiquetaTitulo = new javax.swing.JLabel();
        etiquetaTipoEvento = new javax.swing.JLabel();
        etiquetaDireccion = new javax.swing.JLabel();
        etiquetaAtributosDireccion = new javax.swing.JLabel();
        etiquetaHorarios = new javax.swing.JLabel();
        horarios = new javax.swing.JComboBox<>();
        etiquetaImagen = new javax.swing.JLabel();
        botonComprar = new javax.swing.JButton();
        botonResenia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JavaEvents.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JavaEvents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JavaEvents.setText("JavaEvents");

        etiquetaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaTitulo.setText("Título evento");

        etiquetaTipoEvento.setText("Tipo evento");

        etiquetaDireccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaDireccion.setText("Dirección");

        etiquetaAtributosDireccion.setText("Calle, numero. Ciudad, código postal");

        etiquetaHorarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaHorarios.setText("Horarios disponibles");

        horarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        etiquetaImagen.setText("Imagen");

        botonComprar.setText("Comprar entradas");

        botonResenia.setText("Escribir reseña");
        botonResenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReseniaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JavaEvents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(horarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiquetaHorarios)
                                    .addComponent(etiquetaDireccion)
                                    .addComponent(etiquetaTitulo)
                                    .addComponent(etiquetaTipoEvento)
                                    .addComponent(etiquetaAtributosDireccion)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonComprar)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonResenia))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(etiquetaImagen)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(JavaEvents)
                .addGap(18, 18, 18)
                .addComponent(etiquetaTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaTipoEvento)
                .addGap(18, 18, 18)
                .addComponent(etiquetaDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaAtributosDireccion)
                .addGap(18, 18, 18)
                .addComponent(etiquetaHorarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(horarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiquetaImagen)
                .addGap(179, 179, 179)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonComprar)
                    .addComponent(botonResenia))
                .addGap(46, 46, 46))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonReseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReseniaActionPerformed
        EscribirResenia ventanaResenia = new EscribirResenia();
        ventanaResenia.setEventoElejido(eventoElejido);
        System.out.println("de" + eventoElejido);
        
        this.setVisible(false);
        ventanaResenia.setVisible(true);
    }//GEN-LAST:event_botonReseniaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed"etiquetaAtributosDireccion Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallesEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallesEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallesEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallesEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetallesEvento().setVisible(true);
            }
        });
    }

    // Métodos para cambiar los elementos con la información del evento elejido
    
    public void setEtiquetaTitulo(String texto) {
        etiquetaTitulo.setText(texto);
    }

    public void setEtiquetaTipoEvento(String texto) {
        etiquetaTipoEvento.setText(texto);
    }

    public void setEtiquetaAtributosDireccion(String texto) {
        etiquetaAtributosDireccion.setText(texto);
    }

    public void setHorarios(ArrayList<LocalDateTime> listaHorarios) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

        ArrayList<String> opcionesFormateadas = new ArrayList<>();
        for (LocalDateTime fecha : listaHorarios) {
            opcionesFormateadas.add(fecha.format(formatter));
        }

        horarios.setModel(new DefaultComboBoxModel<>(opcionesFormateadas.toArray(new String[0])));
    }

    public void setImagen(String ruta) {
        etiquetaImagen.setText("");

        ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource(ruta));
        etiquetaImagen.setIcon(icono);
    }
    
    public void setEventoElejido(Evento evento) {
        this.eventoElejido = evento;
    }

    private Evento eventoElejido;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JavaEvents;
    private javax.swing.JButton botonComprar;
    private javax.swing.JButton botonResenia;
    private javax.swing.JLabel etiquetaAtributosDireccion;
    private javax.swing.JLabel etiquetaDireccion;
    private javax.swing.JLabel etiquetaHorarios;
    private javax.swing.JLabel etiquetaImagen;
    private javax.swing.JLabel etiquetaTipoEvento;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JComboBox<String> horarios;
    // End of variables declaration//GEN-END:variables
}
