/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poo.javaevents.ventanas;

import java.awt.Image;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import poo.javaevents.clases.Cliente;
import poo.javaevents.clases.Evento;

/**
 *
 * @author golde
 */
public class DetallesEvento extends javax.swing.JFrame {

    /**
     * Creates new form DetallesEvento
     */
    public DetallesEvento() {
        initComponents();
        setSize(550, 700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JavaEvents = new javax.swing.JLabel();
        etiquetaTitulo = new javax.swing.JLabel();
        etiquetaTipoEvento = new javax.swing.JLabel();
        etiquetaDireccion = new javax.swing.JLabel();
        etiquetaAtributosDireccion = new javax.swing.JLabel();
        etiquetaHorarios = new javax.swing.JLabel();
        horarios = new javax.swing.JComboBox<>();
        imagen = new javax.swing.JLabel();
        botonComprar = new javax.swing.JButton();
        botonResenia = new javax.swing.JButton();
        etiquetaPrecioEntrada = new javax.swing.JLabel();
        etiquetaPrecio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        JavaEvents.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JavaEvents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JavaEvents.setText("JavaEvents");

        etiquetaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        etiquetaTitulo.setText("Título evento");

        etiquetaTipoEvento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiquetaTipoEvento.setText("Tipo evento");

        etiquetaDireccion.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        etiquetaDireccion.setText("Dirección");

        etiquetaAtributosDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiquetaAtributosDireccion.setText("Calle, numero. Ciudad, código postal");

        etiquetaHorarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaHorarios.setText("Horarios disponibles");

        horarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        imagen.setText("Imagen");

        botonComprar.setText("Comprar entradas");
        botonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprarActionPerformed(evt);
            }
        });

        botonResenia.setText("Escribir reseña");
        botonResenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReseniaActionPerformed(evt);
            }
        });

        etiquetaPrecioEntrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaPrecioEntrada.setText("Precio de entrada");

        etiquetaPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiquetaPrecio.setText("Precio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JavaEvents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaDireccion)
                                    .addComponent(etiquetaTitulo)
                                    .addComponent(etiquetaTipoEvento)
                                    .addComponent(etiquetaAtributosDireccion)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonComprar)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonResenia))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(etiquetaHorarios)
                                        .addGap(67, 67, 67)
                                        .addComponent(etiquetaPrecioEntrada)
                                        .addGap(18, 18, 18)
                                        .addComponent(etiquetaPrecio))
                                    .addComponent(horarios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(imagen)))
                        .addGap(0, 97, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(JavaEvents)
                .addGap(18, 18, 18)
                .addComponent(etiquetaTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaTipoEvento)
                .addGap(18, 18, 18)
                .addComponent(etiquetaDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaAtributosDireccion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etiquetaPrecioEntrada)
                        .addComponent(etiquetaPrecio))
                    .addComponent(etiquetaHorarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(horarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(imagen)
                .addGap(179, 179, 179)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonComprar)
                    .addComponent(botonResenia))
                .addGap(46, 46, 46))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonReseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReseniaActionPerformed
        EscribirResenia ventanaResenia = new EscribirResenia();
        ventanaResenia.setEventoElejido(eventoElejido);
        ventanaResenia.ventanaAnterior(this);

        this.setVisible(false);
        ventanaResenia.setVisible(true);
    }//GEN-LAST:event_botonReseniaActionPerformed

    private void botonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprarActionPerformed
        CompraEntradas compraEntradas = new CompraEntradas();

        compraEntradas.setEventoElejido(eventoElejido);
        compraEntradas.setCliente(clienteActual);
        compraEntradas.setHorarios(eventoElejido.getFechasYHoras());
        compraEntradas.setPrecioEntrada(eventoElejido.getPrecioEntrada());
        compraEntradas.setPrecioTotal();

        compraEntradas.ventanaAnterior(this);

        this.setVisible(false);
        compraEntradas.setVisible(true);
    }//GEN-LAST:event_botonComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed"etiquetaAtributosDireccion Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallesEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallesEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallesEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallesEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetallesEvento().setVisible(true);
            }
        });
    }

    // Métodos para cambiar los elementos con la información del evento elejido
    public void setEtiquetaTitulo(String texto) {
        etiquetaTitulo.setText(texto);
    }

    public void setEtiquetaTipoEvento(String texto) {
        etiquetaTipoEvento.setText(texto);
    }

    public void setEtiquetaAtributosDireccion(String texto) {
        etiquetaAtributosDireccion.setText(texto);
    }

    public void setHorarios(ArrayList<LocalDateTime> listaHorarios) {
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

        ArrayList<String> opcionesFormateadas = new ArrayList<>();
        for (LocalDateTime fecha : listaHorarios) {
            opcionesFormateadas.add(fecha.format(formato));
        }

        horarios.setModel(new DefaultComboBoxModel<>(opcionesFormateadas.toArray(new String[0])));
    }

    public void setPrecio(double precio) {
        etiquetaPrecio.setText(precio + " €");
    }

    public void setImagen(String ruta) {
        ImageIcon icono = new ImageIcon(getClass().getResource(ruta));
        Image imagenOriginal = icono.getImage();
        Image imagenEscalada = imagenOriginal.getScaledInstance(256, 256, Image.SCALE_SMOOTH);
        ImageIcon iconoEscalado = new ImageIcon(imagenEscalada);

        imagen.setIcon(iconoEscalado);
        imagen.setText("");

        setLayout(null); // cambiar layout del JFrame para poder mover la imagen
        imagen.setBounds(135, 300, 256, 256); // x, y, ancho, alto
        add(imagen); // añadir el JLabel al JFrame de la ventana
    }
    
    public void imagenNoEncontrada() {
        ImageIcon icono = new ImageIcon(getClass().getResource("/imagenes/imagen_no_encontrada.png"));
        Image imagenOriginal = icono.getImage();
        Image imagenEscalada = imagenOriginal.getScaledInstance(256, 256, Image.SCALE_SMOOTH);
        ImageIcon iconoEscalado = new ImageIcon(imagenEscalada);

        imagen.setIcon(iconoEscalado);
        imagen.setText("");

        setLayout(null); // cambiar layout del JFrame para poder mover la imagen
        imagen.setBounds(135, 300, 256, 256); // x, y, ancho, alto
        add(imagen); // añadir el JLabel al JFrame de la ventana
    }

    public void setEventoElejido(Evento evento) {
        this.eventoElejido = evento;
    }

    public void setCliente(Cliente cliente) {
        this.clienteActual = cliente;
    }

    private Evento eventoElejido;
    private Cliente clienteActual;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JavaEvents;
    private javax.swing.JButton botonComprar;
    private javax.swing.JButton botonResenia;
    private javax.swing.JLabel etiquetaAtributosDireccion;
    private javax.swing.JLabel etiquetaDireccion;
    private javax.swing.JLabel etiquetaHorarios;
    private javax.swing.JLabel etiquetaPrecio;
    private javax.swing.JLabel etiquetaPrecioEntrada;
    private javax.swing.JLabel etiquetaTipoEvento;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JComboBox<String> horarios;
    private javax.swing.JLabel imagen;
    // End of variables declaration//GEN-END:variables
}
