/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.javaevents.ventanas;

import java.awt.Image;
import javax.swing.ImageIcon;
import poo.javaevents.clases.Evento;
import poo.javaevents.clases.Resenia;

/**
 *
 * @author golde
 */
public class EscribirResenia extends javax.swing.JFrame {

    /**
     * Creates new form EscribirReseña
     */
    public EscribirResenia() {
        initComponents();

        setSize(550, 700);

        ImageIcon icono = (ImageIcon) imagenEstrella.getIcon();
        Image imagen = icono.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);
        imagenEstrella.setIcon(new ImageIcon(imagen));
        imagenEstrella.setVisible(false);

        // Hacer que cuando se llegue al límite del área de texto, se pase a la
        // siguiente linea
        textoResenia.setLineWrap(true); // Habilita el ajuste de línea
        textoResenia.setWrapStyleWord(true); // Ajusta al final de las palabras
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        JavaEvents = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoResenia = new javax.swing.JTextArea();
        etiquetaCalificacion = new javax.swing.JLabel();
        imagenEstrella = new javax.swing.JLabel();
        rBoton1 = new javax.swing.JRadioButton();
        rBoton2 = new javax.swing.JRadioButton();
        rBoton3 = new javax.swing.JRadioButton();
        rBoton4 = new javax.swing.JRadioButton();
        rBoton5 = new javax.swing.JRadioButton();
        botonPublicar = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JavaEvents.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JavaEvents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JavaEvents.setText("JavaEvents");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Reseña");

        textoResenia.setColumns(20);
        textoResenia.setRows(5);
        jScrollPane2.setViewportView(textoResenia);

        etiquetaCalificacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaCalificacion.setText("Calificación");

        imagenEstrella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estrella.png"))); // NOI18N

        buttonGroup1.add(rBoton1);
        rBoton1.setText("1 estrella");
        rBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBoton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rBoton2);
        rBoton2.setText("2 estrellas");
        rBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBoton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rBoton3);
        rBoton3.setText("3 estrellas");
        rBoton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBoton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rBoton4);
        rBoton4.setText("4 estrellas");
        rBoton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBoton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rBoton5);
        rBoton5.setText("5 estrellas");
        rBoton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBoton5ActionPerformed(evt);
            }
        });

        botonPublicar.setText("Publicar");
        botonPublicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPublicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JavaEvents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonPublicar)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaCalificacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imagenEstrella, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rBoton1)
                        .addGap(18, 18, 18)
                        .addComponent(rBoton2)
                        .addGap(18, 18, 18)
                        .addComponent(rBoton3)
                        .addGap(18, 18, 18)
                        .addComponent(rBoton4)
                        .addGap(18, 18, 18)
                        .addComponent(rBoton5))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(JavaEvents)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenEstrella, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaCalificacion, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBoton1)
                    .addComponent(rBoton2)
                    .addComponent(rBoton3)
                    .addComponent(rBoton4)
                    .addComponent(rBoton5))
                .addGap(61, 61, 61)
                .addComponent(botonPublicar)
                .addGap(55, 55, 55))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBoton1ActionPerformed
        this.calificacion = 1;
    }//GEN-LAST:event_rBoton1ActionPerformed

    private void rBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBoton2ActionPerformed
        this.calificacion = 2;
    }//GEN-LAST:event_rBoton2ActionPerformed

    private void rBoton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBoton4ActionPerformed
        this.calificacion = 4;
    }//GEN-LAST:event_rBoton4ActionPerformed

    private void rBoton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBoton5ActionPerformed
        this.calificacion = 5;
    }//GEN-LAST:event_rBoton5ActionPerformed

    private void rBoton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBoton3ActionPerformed
        this.calificacion = 3;
    }//GEN-LAST:event_rBoton3ActionPerformed

    private void botonPublicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPublicarActionPerformed
        String descripcion = textoResenia.getText();

        Resenia resenia = 
                new Resenia(this.eventoElejido, this.calificacion, descripcion);
        
        this.eventoElejido.addResenia(resenia);
        
        setVisible(false);
    }//GEN-LAST:event_botonPublicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscribirResenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscribirResenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscribirResenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscribirResenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscribirResenia().setVisible(true);
            }
        });
    }
    
    public void setEventoElejido(Evento evento) {
        this.eventoElejido = evento;
    }

    private int calificacion;
    private Evento eventoElejido;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JavaEvents;
    private javax.swing.JButton botonPublicar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel etiquetaCalificacion;
    private javax.swing.JLabel imagenEstrella;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton rBoton1;
    private javax.swing.JRadioButton rBoton2;
    private javax.swing.JRadioButton rBoton3;
    private javax.swing.JRadioButton rBoton4;
    private javax.swing.JRadioButton rBoton5;
    private javax.swing.JTextArea textoResenia;
    // End of variables declaration//GEN-END:variables
}
